security:
    enable_authenticator_manager: true

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: auto

    providers:
        user_provider:
            id: App\Security\Core\User\UserProvider

    firewalls:

        # Docs
        docs:
            pattern: ^/api/v1/docs
            methods: [GET]
            jwt: ~
            security: false

        # Users
        user_register:
            pattern: ^/api/v1/users/user_register
            methods: [POST]
            security: false
        resend_activation_email:
            pattern: ^/api/v1/users/resend_activation_email
            methods: [POST]
            security: false
        activate_user_account:
            pattern: ^/api/v1/users/.*/activate
            methods: [PUT]
            security: false
        request_reset_password:
            pattern: ^/api/v1/users/request_reset_password
            methods: [POST]
            security: false
        reset_password:
            pattern: ^/api/v1/users/.*/reset_password
            methods: [PUT]
            security: false
        google_oauth:
            pattern: ^/api/v1/users/google/oauth
            methods: [GET]
            custom_authenticators:
                - App\Service\Google\GoogleService
        login:
            pattern: /api/v1/users/login
            provider: user_provider
            stateless: true
            json_login:
                check_path: /api/v1/users/login_check
                success_handler: App\Security\Http\Authentication\AuthenticationSuccessHandler
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        # API
        api:
            pattern: ^/api/v1
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/api/v1/users/google/oauth, roles: PUBLIC_ACCESS }
        - { path: ^/api/v1/users/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/v1/docs, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/v1, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
