resources:
  App\Entity\User:
    operations:
      ApiPlatform\Metadata\Get: ~

      # User register
      user_register:
        class: ApiPlatform\Metadata\Post
        controller: App\Controller\Action\User\Register
        method: POST
        uriTemplate: /users/user_register

        denormalizationContext:
          groups: ['user_register']
        normalizationContext:
          groups: ['user_read']

        openapi:
          summary: Register a new user.

      # Resend activation Email
      resend_activation_email:
        class: ApiPlatform\Metadata\Post
        controller: App\Controller\Action\User\ResendActivationEmail
        deserialize: false
        method: POST
        uriTemplate: /users/resend_activation_email

        openapi:
          summary: Sends activation E-Mail to inactive user.
          requestBody:
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    email:
                      type: string
                      required: true

          responses:
            200:
              description: OK
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      message:
                        type: string

      # Activate user account
      activate_user_account:
        class: ApiPlatform\Metadata\Put
        controller: App\Controller\Action\User\ActivateAccount
        deserialize: false
        method: PUT
        uriTemplate: /users/{id}/activate_user_account

        denormalizationContext:
          groups: ['user_activate']
        normalizationContext:
          groups: ['user_read']

        openapi:
          summary: Activates a user account.

      # Login
      login:
        class: ApiPlatform\Metadata\Post
        method: POST
        routeName: api_login_check

        openapi:
          summary: Login a user in the API.
          requestBody:
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    username:
                      type: string
                    password:
                      type: string

          responses:
            200:
              description: OK
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      token:
                        type: string

      # Request reset password
      request_reset_password:
        class: ApiPlatform\Metadata\Post
        controller: App\Controller\Action\User\RequestResetPassword
        deserialize: false
        method: POST
        uriTemplate: /users/request_reset_password

        openapi:
          summary: Request an E-Mail with a URL to reset a user password.
          requestBody:
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    email:
                      type: string
                      required: true

          responses:
            200:
              description: OK
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      message:
                        type: string

      # Reset password
      reset_password:
        class: ApiPlatform\Metadata\Put
        controller: App\Controller\Action\User\ResetPassword
        deserialize: false
        method: PUT
        uriTemplate: /users/{id}/reset_password

        openapi:
          summary: Reset user password.
          requestBody:
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    resetPasswordToken:
                      type: string
                      required: true
                    password:
                      type: string
                      required: true

          responses:
            200:
              description: OK
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      message:
                        type: string

      # Change password
      change_password:
        class: ApiPlatform\Metadata\Put
        controller: App\Controller\Action\User\ChangePassword
        deserialize: false
        method: PUT
        uriTemplate: /users/{id}/change_password

        openapi:
          summary: Changes user password.
          requestBody:
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    oldPassword:
                      type: string
                      required: true
                    newPassword:
                      type: string
                      required: true
