resources:
  App\Entity\User:
    operations:
      ApiPlatform\Metadata\Get: ~

      # User register
      user_register:
        class: ApiPlatform\Metadata\Post
        controller: App\Controller\Action\User\Register
        method: POST
        uriTemplate: /users/register

        denormalizationContext:
          groups: ['user_register']
        normalizationContext:
          groups: ['user_read']

        openapi:
          summary: Register a new user